version: '3.7'


services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data



  postgres:
    image: postgres:16.2
  advertisement-db:
    image: postgres:16.2
    volumes:
      - advertisement_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${ANOTHER_POSTGRES_DB}
      POSTGRES_USER: ${ANOTHER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ANOTHER_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  photo-db:
    image: postgres:16.2
    volumes:
      - photo_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PHOTO_POSTGRES_DB}
      POSTGRES_USER: ${PHOTO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PHOTO_POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  advertisement_postgres_data:
    driver: local
  photo_postgres_data:
    driver: local
  redis_data:
    driver: local