package com.yelman.blogservices.model.enums;

public enum LanguageEnum {
    TURKISH, ENGLISH, FRENCH, GERMAN,
    ARABIC, BOSNIAN, DANISH, SPANISH,
    DUTCH, CROATIAN, ITALIAN, HUNGARIAN,
    MALAY, NORWEGIAN, POLISH, PORTUGUESE,
    ROMANIAN, RUSSIAN, ALBANIAN, FINNISH,
    UKRAINIAN, GREEK, BULGARIAN, KYRGYZ, MONGOLIAN,
    SERBIAN, ARMENIAN, GEORGIAN, PERSIAN, KAZAKH, HINDI

}
