spring:
  application:
    name: shopping-server
  cloud:
    config:
      enabled: false
  datasource:
    url: ${DB_POSTGRES_URL_FIRST}
    username: ilan_admin
    password: ilan_admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgres

    #Email sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: cihankara632@gmail.com
    password: ovtz mkng waxy bhvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
# security


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
instance:
    preferIpAddress: true


security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
logging:
  level:
    org.hibernate.SQL: DEBUG  # Hibernate SQL sorgular?n? loglar
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL parametrelerini loglar

server:
  port: 8086

