spring:
  security:
    oauth2:
        client:
          registration:
            google:
              client-id: ${CLIENT_ID}
              client-secret: ${CLIENT_SECRET}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp

  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/advertisement_db
    username: ilan_admin
    password: ilan_admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgres
  application:
    name: identity-server
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}

server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    preferIpAddress: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



