spring:
  application:
    name: advertisement-server
  cloud:
    config:
      enabled: false
  datasource:
    url: ${CHARGE_STATION_DB:jdbc:postgresql://localhost:5432/advertisement_db}
    username: ilan_admin
    password: ilan_admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgres


  liquibase:
    change-log: classpath:/db/changelog/masters.yml
    default-schema: public
    #Email sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: cihankara632@gmail.com
    password: ovtz mkng waxy bhvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp




logging:
  level:
    org.hibernate.SQL: DEBUG  # Hibernate SQL sorgular?n? loglar
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL parametrelerini loglar

server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true