spring:
  datasource:
    url: ${CHARGE_STATION_DB:jdbc:postgresql://localhost:5432/advertisement_db}
    username: ilan_admin
    password: ilan_admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      resourceserver:
        public-paths: /v1/users/user-token
        jwt:
          jwk-set-uri: http://localhost:8180/realms/dev/protocol/openid-connect/certs

  liquibase:
    change-log: classpath:/db/changelog/master.yml
server:
  port: 8083  # Uygulama portu

logging:
  level:
    org.hibernate.SQL: DEBUG  # Hibernate SQL sorgularını loglar
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL parametrelerini loglar


