spring:
  application:
    name: blog-server
  cloud:
    config:
      enabled: false
  datasource:
    url: ${CHARGE_STATION_DB:jdbc:postgresql://localhost:5432/advertisement_db}
    username: ilan_admin
    password: ilan_admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgres
server:
  port: 8085  # Uygulama portu

logging:
  level:
    liquibase: DEBUG
    org.hibernate.SQL: DEBUG  # Hibernate SQL sorgular?n? loglar
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL parametrelerini loglar


