spring:
  # Redis cache
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 8
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false
  application:
    name: blog-server
  cloud:
    config:
      enabled: false
  datasource:
      url: ${DB_POSTGRES_URL_FIRST}
      username: ilan_admin
      password: ilan_admin123
      driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgres
server:
  port: 8084  # Uygulama portu
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
logging:
  level:
    liquibase: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    preferIpAddress: true
